export const countries = [
  { name: 'Pakistan', code: 'PK', dial_code: '+92', symbol: '🇵🇰' },
  { name: 'Afghanistan', code: 'AF', dial_code: '+93', symbol: '🇦🇫' },
  { name: 'Algeria', code: 'DZ', dial_code: '+213', symbol: '🇩🇿' },
  { name: 'Argentina', code: 'AR', dial_code: '+54', symbol: '🇦🇷' },
  { name: 'Australia', code: 'AU', dial_code: '+61', symbol: '🇦🇺' },
  { name: 'Bangladesh', code: 'BD', dial_code: '+880', symbol: '🇧🇩' },
  { name: 'Belgium', code: 'BE', dial_code: '+32', symbol: '🇧🇪' },
  { name: 'Botswana', code: 'BW', dial_code: '+267', symbol: '🇧🇼' },
  { name: 'Brazil', code: 'BR', dial_code: '+55', symbol: '🇧🇷' },
  { name: 'Canada', code: 'CA', dial_code: '+1', symbol: '🇨🇦' },
  { name: 'Chile', code: 'CL', dial_code: '+56', symbol: '🇨🇱' },
  { name: 'China', code: 'CN', dial_code: '+86', symbol: '🇨🇳' },
  { name: 'Colombia', code: 'CO', dial_code: '+57', symbol: '🇨🇴' },
  { name: 'Egypt', code: 'EG', dial_code: '+20', symbol: '🇪🇬' },
  { name: 'Ethiopia', code: 'ET', dial_code: '+251', symbol: '🇪🇹' },
  { name: 'France', code: 'FR', dial_code: '+33', symbol: '🇫🇷' },
  { name: 'Germany', code: 'DE', dial_code: '+49', symbol: '🇩🇪' },
  { name: 'Ghana', code: 'GH', dial_code: '+233', symbol: '🇬🇭' },
  { name: 'Greece', code: 'GR', dial_code: '+30', symbol: '🇬🇷' },
  { name: 'Indonesia', code: 'ID', dial_code: '+62', symbol: '🇮🇩' },
  { name: 'Iran', code: 'IR', dial_code: '+98', symbol: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', dial_code: '+964', symbol: '🇮🇶' },
  { name: 'Italy', code: 'IT', dial_code: '+39', symbol: '🇮🇹' },
  { name: 'Japan', code: 'JP', dial_code: '+81', symbol: '🇯🇵' },
  { name: 'Jordan', code: 'JO', dial_code: '+962', symbol: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', dial_code: '+7', symbol: '🇰🇿' },
  { name: 'Kenya', code: 'KE', dial_code: '+254', symbol: '🇰🇪' },
  { name: 'Kuwait', code: 'KW', dial_code: '+965', symbol: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', dial_code: '+996', symbol: '🇰🇬' },
  { name: 'Lebanon', code: 'LB', dial_code: '+961', symbol: '🇱🇧' },
  { name: 'Malaysia', code: 'MY', dial_code: '+60', symbol: '🇲🇾' },
  { name: 'Maldives', code: 'MV', dial_code: '+960', symbol: '🇲🇻' },
  { name: 'Mexico', code: 'MX', dial_code: '+52', symbol: '🇲🇽' },
  { name: 'Mongolia', code: 'MN', dial_code: '+976', symbol: '🇲🇳' },
  { name: 'Morocco', code: 'MA', dial_code: '+212', symbol: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', dial_code: '+258', symbol: '🇲🇿' },
  { name: 'Namibia', code: 'NA', dial_code: '+264', symbol: '🇳🇦' },
  { name: 'Nepal', code: 'NP', dial_code: '+977', symbol: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', dial_code: '+31', symbol: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', dial_code: '+64', symbol: '🇳🇿' },
  { name: 'Nigeria', code: 'NG', dial_code: '+234', symbol: '🇳🇬' },
  { name: 'Norway', code: 'NO', dial_code: '+47', symbol: '🇳🇴' },
  { name: 'Oman', code: 'OM', dial_code: '+968', symbol: '🇴🇲' },
  { name: 'Peru', code: 'PE', dial_code: '+51', symbol: '🇵🇪' },
  { name: 'Philippines', code: 'PH', dial_code: '+63', symbol: '🇵🇭' },
  { name: 'Poland', code: 'PL', dial_code: '+48', symbol: '🇵🇱' },
  { name: 'Portugal', code: 'PT', dial_code: '+351', symbol: '🇵🇹' },
  { name: 'Qatar', code: 'QA', dial_code: '+974', symbol: '🇶🇦' },
  { name: 'Russia', code: 'RU', dial_code: '+7', symbol: '🇷🇺' },
  { name: 'Saudi Arabia', code: 'SA', dial_code: '+966', symbol: '🇸🇦' },
  { name: 'Singapore', code: 'SG', dial_code: '+65', symbol: '🇸🇬' },
  { name: 'South Africa', code: 'ZA', dial_code: '+27', symbol: '🇿🇦' },
  { name: 'South Korea', code: 'KR', dial_code: '+82', symbol: '🇰🇷' },
  { name: 'Spain', code: 'ES', dial_code: '+34', symbol: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', dial_code: '+94', symbol: '🇱🇰' },
  { name: 'Sweden', code: 'SE', dial_code: '+46', symbol: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', dial_code: '+41', symbol: '🇨🇭' },
  { name: 'Syria', code: 'SY', dial_code: '+963', symbol: '🇸🇾' },
  { name: 'Tajikistan', code: 'TJ', dial_code: '+992', symbol: '🇹🇯' },
  { name: 'Tanzania', code: 'TZ', dial_code: '+255', symbol: '🇹🇿' },
  { name: 'Thailand', code: 'TH', dial_code: '+66', symbol: '🇹🇭' },
  { name: 'Turkey', code: 'TR', dial_code: '+90', symbol: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', dial_code: '+993', symbol: '🇹🇲' },
  { name: 'Uganda', code: 'UG', dial_code: '+256', symbol: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', dial_code: '+380', symbol: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', dial_code: '+971', symbol: '🇦🇪' },
  { name: 'Uzbekistan', code: 'UZ', dial_code: '+998', symbol: '🇺🇿' },
  { name: 'Vietnam', code: 'VN', dial_code: '+84', symbol: '🇻🇳' },
  { name: 'Yemen', code: 'YE', dial_code: '+967', symbol: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', dial_code: '+260', symbol: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', dial_code: '+263', symbol: '🇿🇼' }
];
